### ISSUE TITLE
Can't INSERT PointS

### ISSUE THREAD

**Issue by AlekSi** [cridenour/go-postgis#1]
Hello,

I'm using `github.com/lib/pq` and trying to insert PointS into database with code like this:
```go
DB.Exec("INSERT INTO pois (lonlat) VALUES ($1)", postgis.PointS{SRID: 4326, X: 42, Y: 77})
```

It fails with `pq: invalid byte sequence for encoding "UTF8": 0x00`.

**Comment by AlekSi** [comment]
We ended up implementing our own types, and just few days ago started to open-source them there: https://github.com/mc2soft/pq-types/tree/postgis

**Comment by cridenour** [comment]
Perfect timing! You got your first star :)
