### ISSUE TITLE
json: unsupported value: NaN

### ISSUE THREAD

**Issue by selam** [cridenour/go-postgis#5]
I need to convert  as json of Point but json.Marshall returns error with "json: unsupported value: NaN" 

How can i solve this?

**Comment by selam** [comment]
type H struct {
   Id int `json:"id"`
  Point postgis.Point `json:"point"`
} 

...
h := H{}
rows.Scan(&h.Id, &h.Point) ;
json.Marshall(h)

**Comment by cridenour** [comment]
Hi @selam - that's bizarre! The point struct is just a couple of float64. 

Can you print out your result while it's still in Go to ensure it's being read correctly?

**Comment by selam** [comment]
Sorry for bad bug report, 
I just use  "select point from gis_table" as select statement and i get the this error, after looking your test files i realize i was just mis use  your library.

**Comment by cridenour** [comment]
Ah no worries. Glad it's working now!
